### ISSUE TITLE
install exp10it error

### ISSUE THREAD

**Issue by ilovecode2018** [3xp10it/xcdn#2]
Collecting exp10it
  Downloading https://files.pythonhosted.org/packages/33/11/6598105aaa3ec704d7e54acb2a83624abf8141637e727802d1ef1700939c/exp10it-2.6.97.tar.gz (181kB)
    100% |████████████████████████████████| 184kB 35kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\tzk\AppData\Local\Temp\pip-install-br1jouqp\exp10it\setup.py", line 27, in <module>
        LONG_DESCRIPTION = read("README.md")
      File "C:\Users\tzk\AppData\Local\Temp\pip-install-br1jouqp\exp10it\setup.py", line 21, in read
        return codecs.open(os.path.join(os.path.dirname(__file__), fname)).read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 20: illegal multibyte sequence

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\ttt\AppData\Local\Temp\pip-install-br1jouqp\exp10it\
=========================================================================
电脑是win10+python3。但是安装exp10it时报上述错误。换到kali下也是一样。

**Comment by 3xp10it** [comment]
从报错上看估计是用到了pip对应的python2安装，需要在kali下用python3的环境运行：
`pip3 install exp10it`
