### ISSUE TITLE
不清楚这是什么原因在kali里和mac里都报错

### ISSUE THREAD

**Issue by h35h4n9** [3xp10it/xcdn#6]
python3 -m pip install exp10it
Collecting exp10it
  Downloading exp10it-2.7.71.tar.gz (183 kB)
     |████████████████████████████████| 183 kB 279 kB/s 
Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (from exp10it) (0.4.1)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from exp10it) (2.21.0)
Requirement already satisfied: chardet in /usr/lib/python3/dist-packages (from exp10it) (3.0.4)
Requirement already satisfied: pycrypto in /usr/lib/python3/dist-packages (from exp10it) (2.6.1)
Requirement already satisfied: pyperclip in /usr/lib/python3/dist-packages (from exp10it) (1.6.4)
Collecting beepy
  Downloading beepy-1.0.7-py3-none-any.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 707 kB/s 
Collecting bs4
  Downloading bs4-0.0.1.tar.gz (1.1 kB)
Requirement already satisfied: beautifulsoup4 in /usr/lib/python3/dist-packages (from bs4->exp10it) (4.8.0)
Collecting configparser
  Downloading configparser-5.0.1-py3-none-any.whl (22 kB)
Collecting html2text
  Downloading html2text-2020.1.16-py3-none-any.whl (32 kB)
Collecting mechanicalsoup
  Downloading MechanicalSoup-0.12.0-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: lxml in /usr/lib/python3/dist-packages (from mechanicalsoup->exp10it) (4.4.1)
Requirement already satisfied: six>=1.4 in /usr/lib/python3/dist-packages (from mechanicalsoup->exp10it) (1.13.0)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from exp10it) (2.21.0)
Requirement already satisfied: beautifulsoup4 in /usr/lib/python3/dist-packages (from bs4->exp10it) (4.8.0)
Collecting pymysql
  Downloading PyMySQL-0.10.1-py2.py3-none-any.whl (47 kB)
     |████████████████████████████████| 47 kB 953 kB/s 
Collecting selenium
  Downloading selenium-3.141.0-py2.py3-none-any.whl (904 kB)
     |████████████████████████████████| 904 kB 885 kB/s 
Requirement already satisfied: urllib3 in /usr/lib/python3/dist-packages (from selenium->exp10it) (1.24.1)
Collecting simpleaudio
  Downloading simpleaudio-1.0.4.tar.gz (2.0 MB)
     |████████████████████████████████| 2.0 MB 1.0 MB/s 
Collecting wget
  Downloading wget-3.2.zip (10 kB)
Building wheels for collected packages: exp10it, bs4, simpleaudio, wget
  Building wheel for exp10it (setup.py) ... done
  Created wheel for exp10it: filename=exp10it-2.7.71-py3-none-any.whl size=60446 sha256=1d5ae3b71a97307e6e14e74ef5fbfc8a176d2e8f8cf17204a352f15603a6fe60
  Stored in directory: /root/.cache/pip/wheels/f2/8a/bd/73aef3abb29abc641ca3acd37ea4072569b4b54d272be484fe
  Building wheel for bs4 (setup.py) ... done
  Created wheel for bs4: filename=bs4-0.0.1-py3-none-any.whl size=1273 sha256=1ab174d9df36af299e533d3c1b4b3a2aafe4921ba1cc1eace6eabac224fd7b9d
  Stored in directory: /root/.cache/pip/wheels/0a/9e/ba/20e5bbc1afef3a491f0b3bb74d508f99403aabe76eda2167ca
  Building wheel for simpleaudio (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wkgouxao/simpleaudio_48766b3dd2c04c3d9ea24a1b79691e48/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wkgouxao/simpleaudio_48766b3dd2c04c3d9ea24a1b79691e48/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ceqqaya5       
       cwd: /tmp/pip-install-wkgouxao/simpleaudio_48766b3dd2c04c3d9ea24a1b79691e48/                                     
  Complete output (26 lines):                                                                                           
  running bdist_wheel                                                                                                   
  running build                                                                                                         
  running build_py                                                                                                      
  creating build                                                                                                        
  creating build/lib.linux-x86_64-3.7                                                                                   
  creating build/lib.linux-x86_64-3.7/simpleaudio                                                                       
  copying simpleaudio/__init__.py -> build/lib.linux-x86_64-3.7/simpleaudio                                             
  copying simpleaudio/shiny.py -> build/lib.linux-x86_64-3.7/simpleaudio                                                
  copying simpleaudio/functionchecks.py -> build/lib.linux-x86_64-3.7/simpleaudio                                       
  creating build/lib.linux-x86_64-3.7/simpleaudio/test_audio                                                            
  copying simpleaudio/test_audio/c.wav -> build/lib.linux-x86_64-3.7/simpleaudio/test_audio                             
  copying simpleaudio/test_audio/e.wav -> build/lib.linux-x86_64-3.7/simpleaudio/test_audio                             
  copying simpleaudio/test_audio/g.wav -> build/lib.linux-x86_64-3.7/simpleaudio/test_audio                             
  copying simpleaudio/test_audio/left_right.wav -> build/lib.linux-x86_64-3.7/simpleaudio/test_audio                    
  copying simpleaudio/test_audio/notes_2_16_44.wav -> build/lib.linux-x86_64-3.7/simpleaudio/test_audio                 
  running build_ext                                                                                                     
  building 'simpleaudio._simpleaudio' extension                                                                         
  creating build/temp.linux-x86_64-3.7                                                                                  
  creating build/temp.linux-x86_64-3.7/c_src                                                                            
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DDEBUG=0 -I/usr/include/python3.7m -c c_src/simpleaudio_alsa.c -o build/temp.linux-x86_64-3.7/c_src/simpleaudio_alsa.o                                                                                          
  In file included from c_src/simpleaudio_alsa.c:7:                                                                     
  c_src/simpleaudio.h:10:10: fatal error: Python.h: 没有那个文件或目录                                                  
     10 | #include <Python.h>                                                                                           
        |          ^~~~~~~~~~                                                                                           
  compilation terminated.                                                                                               
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1                                                       
  ----------------------------------------                                                                              
  ERROR: Failed building wheel for simpleaudio
  Running setup.py clean for simpleaudio
  Building wheel for wget (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9680 sha256=6ad2911d90b7c3a9a21a129e07ca672b708c9d0d3d1a7d7f7a199d89d6790c08
  Stored in directory: /root/.cache/pip/wheels/a1/b6/7c/0e63e34eb06634181c63adacca38b79ff8f35c37e3c13e3c02
Successfully built exp10it bs4 wget
Failed to build simpleaudio
Installing collected packages: simpleaudio, wget, selenium, pymysql, mechanicalsoup, html2text, configparser, bs4, beepy, exp10it
    Running setup.py install for simpleaudio ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wkgouxao/simpleaudio_48766b3dd2c04c3d9ea24a1b79691e48/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wkgouxao/simpleaudio_48766b3dd2c04c3d9ea24a1b79691e48/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-xsbthron/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7/simpleaudio                                                                                                                      
         cwd: /tmp/pip-install-wkgouxao/simpleaudio_48766b3dd2c04c3d9ea24a1b79691e48/                                   
    Complete output (26 lines):                                                                                         
    running install                                                                                                     
    running build                                                                                                       
    running build_py                                                                                                    
    creating build                                                                                                      
    creating build/lib.linux-x86_64-3.7                                                                                 
    creating build/lib.linux-x86_64-3.7/simpleaudio                                                                     
    copying simpleaudio/__init__.py -> build/lib.linux-x86_64-3.7/simpleaudio                                           
    copying simpleaudio/shiny.py -> build/lib.linux-x86_64-3.7/simpleaudio                                              
    copying simpleaudio/functionchecks.py -> build/lib.linux-x86_64-3.7/simpleaudio                                     
    creating build/lib.linux-x86_64-3.7/simpleaudio/test_audio                                                          
    copying simpleaudio/test_audio/c.wav -> build/lib.linux-x86_64-3.7/simpleaudio/test_audio                           
    copying simpleaudio/test_audio/e.wav -> build/lib.linux-x86_64-3.7/simpleaudio/test_audio                           
    copying simpleaudio/test_audio/g.wav -> build/lib.linux-x86_64-3.7/simpleaudio/test_audio                           
    copying simpleaudio/test_audio/left_right.wav -> build/lib.linux-x86_64-3.7/simpleaudio/test_audio                  
    copying simpleaudio/test_audio/notes_2_16_44.wav -> build/lib.linux-x86_64-3.7/simpleaudio/test_audio               
    running build_ext                                                                                                   
    building 'simpleaudio._simpleaudio' extension                                                                       
    creating build/temp.linux-x86_64-3.7                                                                                
    creating build/temp.linux-x86_64-3.7/c_src                                                                          
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DDEBUG=0 -I/usr/include/python3.7m -c c_src/simpleaudio_alsa.c -o build/temp.linux-x86_64-3.7/c_src/simpleaudio_alsa.o                                                                                        
    In file included from c_src/simpleaudio_alsa.c:7:                                                                   
    c_src/simpleaudio.h:10:10: fatal error: Python.h: 没有那个文件或目录                                                
       10 | #include <Python.h>                                                                                         
          |          ^~~~~~~~~~                                                                                         
    compilation terminated.                                                                                             
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1                                                     
    ----------------------------------------                                                                            
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wkgouxao/simpleaudio_48766b3dd2c04c3d9ea24a1b79691e48/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wkgouxao/simpleaudio_48766b3dd2c04c3d9ea24a1b79691e48/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-xsbthron/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7/simpleaudio Check the logs for full command output.

**Comment by 2001hurc** [comment]
解决了吗，我也有这个问题

**Comment by 3xp10it** [comment]
试试`pip3 install exp10it -U --no-cache-dir`
